package server.connection;

import server.Main;

import java.sql.*;

public class DatabaseManager {
    // Table names
    public static final String STUDY_GROUP_TABLE = "study_groups";
    public static final String USER_TABLE = "users";
    public static final String COORDINATES_TABLE = "coordinates";
    public static final String PERSON_TABLE = "person";
    // STUDY_GROUP column names
     /*
    CREATE TABLE study_groups(
            id SERIAL PRIMARY KEY,
            name           CHAR(50)    NOT NULL,
            coordinates_id INT,
            creation_date        TIMESTAMP,
            students_count      INT,
            expelled_students      INT,
            average_mark        INT,
            semester            CHAR(50),
            group_admin_id        INT,
            user_id             INT
    );
      */
    public static final String STUDY_GROUP_TABLE_ID_COLUMN = "id";
    public static final String STUDY_GROUP_TABLE_NAME_COLUMN = "name";
    public static final String STUDY_GROUP_TABLE_COORDINATES_ID = "coordinates_id";
    public static final String STUDY_GROUP_TABLE_CREATION_DATE_COLUMN = "creation_date";
    public static final String STUDY_GROUP_TABLE_STUDENTS_COUNT_COLUMN = "students_count";
    public static final String STUDY_GROUP_TABLE_EXPELLED_STUDENTS_COLUMN = "expelled_students";
    public static final String STUDY_GROUP_TABLE_AVERAGE_MARK_COLUMN = "average_mark";
    public static final String STUDY_GROUP_TABLE_SEMESTER_COLUMN = "semester";
    public static final String STUDY_GROUP_TABLE_GROUP_ADMIN_ID_COLUMN = "group_admin_id";
    public static final String STUDY_GROUP_TABLE_USER_ID_COLUMN = "user_id";
    // USER_TABLE column names
    public static final String USER_TABLE_ID_COLUMN = "id";
    public static final String USER_TABLE_USERNAME_COLUMN = "username";
    public static final String USER_TABLE_PASSWORD_COLUMN = "password";
    // COORDINATES_TABLE column names
    public static final String COORDINATES_TABLE_ID_COLUMN = "id";
    public static final String COORDINATES_TABLE_X_COLUMN = "x";
    public static final String COORDINATES_TABLE_Y_COLUMN = "y";
    // PERSON_TABLE column names
    public static final String PERSON_TABLE_ID_COLUMN = "id";
    public static final String PERSON_TABLE_NAME_COLUMN = "name";
    public static final String PERSON_TABLE_BIRTHDAY_COLUMN = "birthday";
    public static final String PERSON_TABLE_WEIGHT_COLUMN = "weight";
    public static final String PERSON_TABLE_PASSPORT_ID_COLUMN = "passport_id";
    /*
    CREATE TABLE person(
            id SERIAL PRIMARY KEY,
            name           CHAR(50)    NOT NULL,
            birthday            TIMESTAMP     NOT NULL,
            weight        INT,
            passport_id         CHAR(50)
    );

    CREATE TABLE coordinates(
            id SERIAL PRIMARY KEY,
            x INT,
            y INT
    );

    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        username VARCHAR ( 50 ) UNIQUE NOT NULL,
        password VARCHAR ( 50 ) NOT NULL
       );

     */

    private final String JDBC_DRIVER = "org.postgresql.Driver";

    private String url;
    private String user;
    private String password;
    private Connection base;

    public DatabaseManager(String ur, String usr, String pass) {
        url = ur;
        user = usr;
        password = pass;

        connectToDataBase();
    }

    private void connectToDataBase() {
        try {
            Class.forName(JDBC_DRIVER);
            base = DriverManager.getConnection(url, user, password);
            Main.logger.info("Соединение с базой данных установлено.");
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при подключении к базе данных!");
        } catch (ClassNotFoundException exception) {
            Main.logger.error("Драйвер управления базой дынных не найден!");
        }
    }

    public PreparedStatement getPreparedStatement(String sqlStatement, boolean generateKeys) {
        PreparedStatement preparedStatement;
        try {
            if (base == null) throw new SQLException();
            int autoGeneratedKeys = generateKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS;
            preparedStatement = base.prepareStatement(sqlStatement, autoGeneratedKeys);
            Main.logger.info("Подготовлен SQL запрос '" + sqlStatement + "'.");
            return preparedStatement;
        } catch (SQLException exception) {
            if (base == null) Main.logger.error("Соединение с базой данных не установлено!");
        }
        return null;
    }


    public void closePreparedStatement(PreparedStatement sqlStatement) {
        if (sqlStatement == null) return;
        try {
            sqlStatement.close();
            Main.logger.info("Закрыт SQL запрос '" + sqlStatement + "'.");
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при закрытии SQL запроса '" + sqlStatement + "'.");
        }
    }

    public void closeConnection() {
        if (base == null) return;
        try {
            base.close();
            Main.logger.info("Соединение с базой данных разорвано.");
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при разрыве соединения с базой данных!");
        }
    }

    public void setCommitMode() {
        try {
            if (base == null) throw new SQLException();
            base.setAutoCommit(false);
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при установлении режима транзакции базы данных!");
        }
    }

    public void setNormalMode() {
        try {
            if (base == null) throw new SQLException();
            base.setAutoCommit(true);
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при установлении нормального режима базы данных!");
        }
    }

    public void commit() {
        try {
            if (base == null) throw new SQLException();
            base.commit();
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при подтверждении нового состояния базы данных!");
        }
    }

    public void rollback() {
        try {
            if (base == null) throw new SQLException();
            base.rollback();
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при возврате исходного состояния базы данных!");
        }
    }

    public void setSavepoint() {
        try {
            if (base == null) throw new SQLException();
            base.setSavepoint();
        } catch (SQLException exception) {
            Main.logger.error("Произошла ошибка при сохранении состояния базы данных!");
        }
    }
}

